import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { mkdir } from 'node:fs/promises';
const base = process.env.BASE_URL || 'http://ihb.test:8080';
const browser = await chromium.launch({ headless: true, args: ['--no-sandbox'] });
const errors = [];
const context = await browser.newContext({ viewport: { width: 1440, height: 960 }, colorScheme: 'light' });
context.setDefaultTimeout(30000);
context.setDefaultNavigationTimeout(30000);
const page = await context.newPage();
const cssRequests = [];
const cssFailures = [];
function trackStyles(target, requests) {
  target.on('request', request => {
    if (new URL(request.url()).pathname.endsWith('.css')) requests.push(new URL(request.url()).pathname);
  });
  target.on('response', response => {
    if (new URL(response.url()).pathname.endsWith('.css') && !response.ok()) cssFailures.push(response.url());
  });
}
trackStyles(page, cssRequests);
const stylePath = component => `/Components/${component}.razor.rz.scp.css`;
// Capture the existing Leaflet instance in the test browser so geographic clicks are deterministic.
await page.addInitScript(() => {
  let leaflet;
  Object.defineProperty(window, 'L', {
    configurable: true, get: () => leaflet, set: value => {
      leaflet = value; const create = value.map;
      value.map = (...args) => { const map = create(...args); window.__testMap = map; return map; };
    }
  });
});
page.on('pageerror', e => errors.push(e.message));
let checks = 0;
function check(v, msg) { assert.ok(v, msg); checks++; }
async function eventually(fn, msg, timeout = 20000) { const end = Date.now() + timeout; while (Date.now() < end) { if (await fn()) return; await new Promise(r => setTimeout(r, 200)); } throw new Error(msg); }
async function mapView(lat, lng, zoom) {
  await page.evaluate(([lat, lng, zoom]) => window.__testMap.setView([lat, lng], zoom, { animate: false }), [lat, lng, zoom]);
  await page.waitForFunction(zoom => window.__testMap.getZoom() === zoom, zoom);
}
async function clickPlace(lat, lng) {
  const point = await page.evaluate(([lat, lng]) => { const map = window.__testMap, point = map.latLngToContainerPoint([lat, lng]), rect = map.getContainer().getBoundingClientRect(); const clicked = map.containerPointToLatLng(point); return { x: rect.left + point.x, y: rect.top + point.y, lat: clicked.lat, lng: clicked.lng }; }, [lat, lng]);
  await page.mouse.click(point.x, point.y); return point;
}
async function theme(value, target = page) {
  await target.getByRole('button', { name: value === 'dark' ? 'Dark' : 'Light', exact: true }).click();
  await eventually(async () => await target.locator('html').getAttribute('data-theme') === value, 'Theme did not change');
}
try {
  const preferenceContext = await browser.newContext({ colorScheme: 'dark' }), preferences = await preferenceContext.newPage();
  const authStyles = []; trackStyles(preferences, authStyles);
  await preferences.goto(base + '/login');
  check(authStyles.includes(stylePath('Layout/AuthShell')) && authStyles.includes(stylePath('Layout/ThemeSwitcher')) && !authStyles.some(path => path.includes('/Map/') || path.includes('/Journal/') || path.includes('leaflet.css')), 'Login loads its own component styles without journal or Leaflet CSS');
  check(await preferences.locator('.auth-shell').evaluate(element => getComputedStyle(element).display) === 'grid', 'Auth companion CSS styles the initial server-rendered page');
  check(await preferences.locator('html').getAttribute('data-theme') === 'dark', 'Theme defaults to the device preference');
  await theme('light', preferences); await preferences.reload();
  check(await preferences.locator('html').getAttribute('data-theme') === 'light', 'Chosen theme survives a reload');
  await preferences.emulateMedia({ colorScheme: 'light' }); await preferences.emulateMedia({ colorScheme: 'dark' });
  check(await preferences.locator('html').getAttribute('data-theme') === 'light', 'Explicit theme takes precedence over device changes');
  await preferences.goto(base + '/login?theme=dark');
  check(await preferences.locator('html').getAttribute('data-theme') === 'dark', 'Theme URL preference matches Been'); await preferenceContext.close();
  const restrictedContext = await browser.newContext({ colorScheme: 'dark' }), restricted = await restrictedContext.newPage();
  await restricted.addInitScript(() => Object.defineProperty(window, 'localStorage', { get() { throw new Error('Storage disabled'); } }));
  await restricted.goto(base + '/login'); await theme('light', restricted);
  check(await restricted.locator('html').getAttribute('data-theme') === 'light', 'Theme controls work with browser storage disabled'); await restrictedContext.close();
  console.log('Theme preference checks passed; testing map selection and zoom gating.');
  await page.goto(base + '/register');
  await page.getByLabel('Your name').fill('Browser traveler');
  await page.getByLabel('Email', { exact: true }).fill(`${randomUUID()}@example.test`);
  await page.getByLabel('Password', { exact: true }).fill('Travel-Test!2026');
  cssRequests.length = 0;
  await page.getByRole('button', { name: 'Start my journal' }).click();
  await page.waitForURL(base + '/');
  await eventually(async () => await page.locator('#map .leaflet-interactive').count() >= 298, 'Country polygons did not render');
  check(await page.locator('#map .leaflet-interactive').count() >= 298, 'Detailed country polygons rendered');
  check(['Map/MapCanvas', 'Map/MapHeader', 'Journal/JournalPanel', 'Layout/ThemeSwitcher'].every(component => cssRequests.includes(stylePath(component))), 'Initial journal loads the visible components');
  check(cssRequests.includes(stylePath('Journal/JournalShell')) && await page.locator('[data-journal-panel]').evaluate(panel => panel.open), 'Desktop journal keeps its full sidebar and loads the shared presentation shell');
  check(!cssRequests.some(path => /AuthShell|DialogShell|MemoryDetails|ExperienceEditor|StarRating|ShareDialog|\.styles\.css/.test(path)), 'Initial journal omits auth, hidden dialogs, details, stars, and the combined stylesheet');
  check(await page.locator('.journal-panel .notice').count() === 0, 'No notice shown without an error');
  const before = await page.locator('#map .leaflet-map-pane').getAttribute('style');
  await page.mouse.move(900, 700); await page.mouse.down(); await page.mouse.move(1000, 730, { steps: 12 }); await page.mouse.up();
  const after = await page.locator('#map .leaflet-map-pane').getAttribute('style'); check(before !== after, 'World map can be dragged');
  await mapView(-15, -47, 2); await clickPlace(-15, -47);
  const brazil = page.locator('.country-shape[data-country="Brazil"]');
  await eventually(async () => await brazil.getAttribute('aria-pressed') === 'true', 'Country was not selected');
  await page.waitForFunction(() => !window.__testMap._panAnim?._inProgress);
  check(await page.locator('.modal').count() === 0 && await page.evaluate(() => window.__testMap.getZoom()) === 2, 'Country selection preserves zoom and does not open editor');
  check(await brazil.evaluate(path => getComputedStyle(path).outlineStyle) === 'none', 'Country selection has no rectangular browser outline');
  await mapView(-15, -47, 2); await clickPlace(-15, -47);
  check(await page.locator('.modal').count() === 0 && (await page.locator('#map-status').textContent()).includes('Zoom in closer'), 'Repeated clicks at world zoom ask for precise placement');
  await mapView(-15, -47, 7); await clickPlace(-15, -47); check(await page.locator('.modal').count() === 0, 'Zoom level 7 cannot create a map pin');
  await page.locator('.leaflet-control-zoom-in').click(); await page.waitForFunction(() => window.__testMap.getZoom() === 8 && !window.__testMap._animatingZoom);
  const chosenPlace = await clickPlace(-15, -47); await page.getByRole('dialog').waitFor();
  await eventually(async () => await page.locator('.modal-backdrop').evaluate(element => getComputedStyle(element).position) === 'fixed', 'Dialog stylesheet did not load');
  check(cssRequests.includes(stylePath('Layout/DialogShell')) && !cssRequests.includes(stylePath('Sharing/ShareDialog')), 'Opening the memory editor loads dialog CSS without downloading sharing CSS');
  check(await page.getByLabel('Country', { exact: true }).inputValue() === 'Brazil' && Math.abs(Number(await page.getByLabel('Latitude', { exact: true }).inputValue()) - chosenPlace.lat) < 0.000001 && Math.abs(Number(await page.getByLabel('Longitude', { exact: true }).inputValue()) - chosenPlace.lng) < 0.000001, 'Zoom level 8 opens editor at the exact clicked coordinates');
  await page.getByRole('button', { name: 'Close editor', exact: true }).click(); await eventually(async () => await page.locator('.modal').count() === 0, 'Pin editor did not close');
  await mapView(-34.6, -58.4, 8); await clickPlace(-34.6, -58.4);
  await eventually(async () => await page.locator('.country-shape[data-country="Argentina"]').getAttribute('aria-pressed') === 'true', 'Second country was not selected');
  check(await page.locator('.modal').count() === 0, 'A different country needs selection before pin placement, even at high zoom');
  await page.locator('.country-shape[data-country="Argentina"]').focus(); await page.keyboard.press('Enter');
  check(await page.locator('.modal').count() === 0 && await page.locator('.country-shape[data-country="Argentina"]').evaluate(path => getComputedStyle(path).strokeWidth) === '3px', 'Keyboard selection uses a polygon focus border');
  console.log('Country selection and zoom checks passed; testing journal, media, and shared view.');
  await mapView(20, 0, 2);
  await page.getByRole('button', { name: 'Add a memory', exact: false }).click();
  await page.getByLabel('Title', { exact: true }).fill('A browser memory');
  await page.getByLabel('City', { exact: true }).fill('Rio de Janeiro');
  await page.getByLabel('Country', { exact: true }).fill('Brazil');
  await page.getByLabel('The story').fill('A detailed travel memory.');
  await page.getByLabel('Latitude', { exact: true }).fill('-22.9068'); await page.getByLabel('Longitude', { exact: true }).fill('-43.1729');
  await page.getByLabel('Include this memory').check();
  await page.getByRole('button', { name: 'Save memory' }).click();
  await eventually(async () => !(await page.locator('.modal').count()) && await page.locator('.detail-panel h2').textContent() === 'A browser memory', 'C# memory save failed');
  check(await page.locator('.log-card').count() === 1, 'Memory appeared in journal');
  check(cssRequests.includes(stylePath('Journal/MemoryDetails')) && !cssRequests.includes(stylePath('Experiences/StarRating')), 'Memory details load when opened; an empty experience list needs no star CSS');
  const png = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIHWP4z8DwHwAFgAI/ScLbtAAAAABJRU5ErkJggg==', 'base64');
  await page.locator('#media-files').setInputFiles([{ name: 'photo.png', mimeType: 'image/png', buffer: png }, { name: 'another-photo.png', mimeType: 'image/png', buffer: png }]);
  await eventually(async () => await page.locator('.media-grid img').count() === 2, 'Multi-file upload did not appear');
  check(await page.locator('.media-grid img').count() === 2, 'Multiple original photos uploaded');
  await theme('dark');
  check(await page.locator('.leaflet-tile-pane').evaluate(element => getComputedStyle(element).filter) !== 'none', 'Dark theme changes map tiles');
  check(await page.locator('.media-grid img').first().evaluate(element => getComputedStyle(element).filter) === 'none', 'Dark theme does not filter private original photos');
  check(await page.locator('.visited-pin[fill="#36c57e"]').count() === 1, 'Country and marker palette follows dark theme');
  await mkdir('output', { recursive: true }); await page.screenshot({ path: 'output/dark-world.png' });
  await theme('light'); check(await page.getByRole('button', { name: 'Light', exact: true }).getAttribute('aria-pressed') === 'true', 'Theme controls expose their selected state');
  await page.getByRole('button', { name: 'Edit memory', exact: true }).click();
  await page.getByLabel('Title', { exact: true }).fill('An edited memory'); await page.getByRole('button', { name: 'Save memory' }).click();
  await eventually(async () => await page.locator('.detail-panel h2').textContent() === 'An edited memory', 'Memory edit failed'); checks++;
  await page.getByRole('button', { name: 'Add experience', exact: false }).click();
  await eventually(async () => await page.locator('.star-button').first().evaluate(element => getComputedStyle(element).fontSize) === '29px', 'Star companion CSS did not load');
  check(cssRequests.includes(stylePath('Experiences/ExperienceEditor')) && cssRequests.includes(stylePath('Experiences/StarRating')), 'The experience editor automatically loads its nested star component CSS');
  check((await page.locator('#experience-title').locator('..').textContent()).includes('Rio de Janeiro'), 'Experience editor shows its actual city');
  await page.getByLabel('Experience title', { exact: true }).fill('A wonderful museum');
  await page.getByLabel('Category', { exact: true }).selectOption('Museum');
  await page.getByRole('button', { name: '5 stars', exact: true }).click();
  await page.getByLabel('Experience story', { exact: true }).fill('A city sub log.');
  await page.getByRole('button', { name: 'Save experience' }).click();
  await eventually(async () => await page.locator('.experience-card').count() === 1 && !(await page.locator('.modal').count()), 'Experience creation failed');
  check(await page.locator('.experience-card').getByRole('img', { name: '5 out of 5 stars' }).count() === 1, 'Five-star experience saved');
  await page.getByRole('button', { name: 'Edit experience', exact: true }).click();
  await page.getByRole('button', { name: '0 stars', exact: true }).click(); await page.getByRole('button', { name: 'Save experience' }).click();
  await eventually(async () => await page.locator('.experience-card').getByRole('img', { name: '0 out of 5 stars' }).count() === 1 && !(await page.locator('.modal').count()), 'Zero-star edit failed'); checks++;
  await page.getByRole('button', { name: 'Add a wish', exact: false }).click();
  await page.getByLabel('Title', { exact: true }).fill('Japan someday'); await page.getByLabel('Country', { exact: true }).fill('Japan');
  await page.getByLabel('Latitude', { exact: true }).fill('36'); await page.getByLabel('Longitude', { exact: true }).fill('138');
  await page.getByRole('button', { name: 'Save wish' }).click();
  await eventually(async () => !(await page.locator('.modal').count()) && await page.locator('.detail-panel h2').textContent() === 'Japan someday', 'Country wishlist save failed');
  check(await page.locator('.log-card.wishlist').count() === 1, 'Country wishlist appears in journal');
  check(await page.locator('#map .wishlist-pin[fill="#f5ca42"]').count() === 1, 'Wishlist marker is yellow');
  check(await page.locator('#map path[fill="#f5ca42"]').count() > 1, 'Wishlist country polygons are yellow');
  await page.getByRole('button', { name: 'Mark as visited' }).click(); await page.getByLabel('City', { exact: true }).fill('Kyoto');
  await page.getByRole('button', { name: 'Save memory' }).click();
  await eventually(async () => !(await page.locator('.modal').count()) && await page.locator('#map .wishlist-pin').count() === 0, 'Wishlist conversion failed');
  check(await page.locator('#map .visited-pin[fill="#1f8a5b"]').count() === 2, 'Visited wishlist entry turns green');
  await page.getByRole('button', { name: 'Add a wish', exact: false }).click(); await page.getByLabel('Title', { exact: true }).fill('Paris someday');
  await page.getByLabel('City', { exact: true }).fill('Paris'); await page.getByLabel('Country', { exact: true }).fill('France');
  await page.getByLabel('Planned date (optional)').fill('2027-05-01'); await page.getByRole('button', { name: 'Save wish' }).click();
  await eventually(async () => !(await page.locator('.modal').count()) && await page.locator('.detail-panel h2').textContent() === 'Paris someday', 'City wishlist save failed');
  check(await page.locator('.log-card.wishlist').count() === 1, 'City wishlist saved with planned date');
  await page.getByRole('button', { name: 'Wishlist', exact: true }).click(); await eventually(async () => await page.locator('.log-card').count() === 1, 'Wishlist filter did not render'); check(await page.locator('.log-card.wishlist').count() === 1, 'Wishlist filter works');
  await page.getByRole('button', { name: 'All', exact: true }).click(); await eventually(async () => await page.locator('.log-card').count() === 3, 'All places did not render'); await page.getByRole('button', { name: 'An edited memory', exact: false }).click();
  await eventually(async () => await page.locator('.detail-panel h2').textContent() === 'An edited memory', 'Memory selection failed');
  check(!cssRequests.includes(stylePath('Sharing/ShareDialog')), 'Sharing CSS remains unloaded until sharing is opened');
  await page.getByRole('button', { name: 'Share my map' }).click();
  await eventually(async () => cssRequests.includes(stylePath('Sharing/ShareDialog')), 'Sharing CSS did not load');
  check(await page.locator('.modal-backdrop').evaluate(element => getComputedStyle(element).position) === 'fixed', 'Reopened dialogs remain styled');
  check(await page.getByLabel('Copy this link now').count() === 0, 'No invitation URL shown before creation');
  await page.getByLabel('Access lasts').selectOption('never'); await page.getByRole('button', { name: 'Create private link' }).click();
  await eventually(async () => await page.getByLabel('Copy this link now').count() === 1, 'Invitation not created');
  const invitation = await page.getByLabel('Copy this link now').inputValue();
  const visitorContext = await browser.newContext({ viewport: { width: 1280, height: 850 } }); const visitor = await visitorContext.newPage(); visitor.on('pageerror', e => errors.push(e.message));
  const sharedStyles = []; trackStyles(visitor, sharedStyles);
  await visitor.goto(invitation);
  await eventually(async () => await visitor.locator('#shared-logs .log-card').count() === 1, 'Shared journal did not open');
  check(!visitor.url().includes('#'), 'Invitation secret removed from address bar');
  check(sharedStyles.includes(stylePath('Journal/JournalPanel')) && !sharedStyles.some(path => /MemoryDetails|DialogShell|ExperienceEditor|StarRating|ShareDialog|AuthShell/.test(path)), 'The shared journal loads its list styles without owner dialogs or unopened details');
  await visitor.getByRole('button', { name: 'An edited memory' }).click();
  await eventually(async () => await visitor.locator('#shared-detail img').count() === 2, 'Shared media did not render');
  check(await visitor.locator('#shared-detail img').count() === 2, 'Read-only invitation displays shared media');
  check(await visitor.locator('#shared-detail .experience-card').getByRole('img', { name: '0 out of 5 stars' }).count() === 1, 'Shared city experience displays zero-star rating');
  check(['Journal/MemoryDetails', 'Experiences/ExperienceList', 'Experiences/StarRating'].every(component => sharedStyles.includes(stylePath(component))), 'Opening a shared memory loads the same presentation styles as the owner components');
  check(await visitor.locator('#shared-detail .star-display').evaluate(element => getComputedStyle(element).fontSize) === '23px' && await visitor.locator('#shared-detail').evaluate(element => getComputedStyle(element).position) === 'fixed', 'Shared JavaScript content receives the reused component styles');
  await mkdir('output', { recursive: true });
  await theme('dark', visitor); check(await visitor.locator('html').getAttribute('data-theme') === 'dark' && await visitor.locator('#shared-detail img').count() === 2, 'Shared viewer has independent theme controls and keeps media');
  await visitor.screenshot({ path: 'output/shared-map.png' });
  await visitor.setViewportSize({ width: 390, height: 844 });
  await eventually(async () => !await visitor.locator('[data-journal-panel]').evaluate(panel => panel.open), 'Shared mobile journal did not collapse');
  check(await visitor.locator('.journal-metrics strong').allTextContents().then(values => values.join(',') === '1,1,0'), 'Shared compact metrics count only the included memories');
  await visitor.locator('.journal-summary').click();
  check(await visitor.locator('[data-journal-panel]').evaluate(panel => panel.open) && await visitor.locator('#shared-logs .log-card').isVisible(), 'Shared mobile card opens the complete read-only journal');
  await visitor.screenshot({ path: 'output/shared-mobile-journal.png' });
  await visitor.locator('#shared-logs .log-card').click();
  await eventually(async () => !await visitor.locator('[data-journal-panel]').evaluate(panel => panel.open), 'Selecting a shared memory did not collapse the journal');
  check(await visitor.locator('#shared-detail img').count() === 2, 'Shared mobile memory selection leaves its original media visible');
  await page.getByRole('button', { name: 'Revoke', exact: true }).click();
  await eventually(async () => await page.getByRole('button', { name: 'Revoke', exact: true }).count() === 0, 'Revocation did not complete');
  const denied = await visitor.request.get(base + '/api/shared/' + new URL(invitation).pathname.split('/').pop() + '/logs'); check(denied.status() === 404, 'Revoked invitation denied by server');
  await eventually(async () => await visitor.locator('#shared-detail img').count() === 0, 'Revoked viewer did not clear media', 22000); checks++;
  check(await visitor.locator('.journal-metrics strong').allTextContents().then(values => values.every(value => value === '0')), 'Revocation clears shared compact metrics');
  check(await visitor.locator('#shared-status').isVisible(), 'Revocation reveals the unavailable-journal message on mobile');
  await page.getByRole('button', { name: 'Close sharing' }).click();
  page.once('dialog', dialog => dialog.accept());
  await page.getByRole('button', { name: 'Delete experience', exact: true }).click();
  await eventually(async () => await page.locator('.experience-card').count() === 0, 'Experience deletion failed'); checks++;
  await page.getByRole('button', { name: 'Close memory' }).click();
  await eventually(async () => await page.locator('.detail-panel').count() === 0, 'Memory panel did not close');
  await page.screenshot({ path: 'output/my-world.png' });
  console.log('Desktop and shared journal checks passed; testing the compact mobile journal.');
  await page.setViewportSize({ width: 390, height: 844 });
  const journal = page.locator('[data-journal-panel]'), summary = page.locator('.journal-summary');
  await eventually(async () => !await journal.evaluate(panel => panel.open), 'Mobile journal did not collapse');
  check(!await page.locator('.journal-content').isVisible() && (await journal.boundingBox()).height < 120, 'Mobile journal is a compact metrics-only card');
  check(await page.locator('.journal-metrics strong').allTextContents().then(values => values.join(',') === '2,2,1'), 'Owner compact card shows visited countries, memories and wishlist totals');
  check((await page.locator('.leaflet-control-zoom').boundingBox()).y + (await page.locator('.leaflet-control-zoom').boundingBox()).height < (await journal.boundingBox()).y, 'Mobile zoom buttons sit above the measured compact card');
  await page.screenshot({ path: 'output/mobile-world.png' });
  check(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'Mobile layout fits viewport');
  await summary.focus();await page.keyboard.press('Enter');
  check(await journal.evaluate(panel => panel.open) && await page.locator('.log-list .log-card').first().isVisible(), 'Enter on the mobile metrics card opens the full journal');
  await page.getByRole('button', { name: 'Wishlist', exact: true }).click();
  await eventually(async () => await page.locator('.log-card').count() === 1, 'Mobile wishlist filter did not render');
  check(await journal.evaluate(panel => panel.open) && await page.locator('.log-card.wishlist').isVisible(), 'Filtering keeps the expanded mobile journal open');
  await page.getByRole('button', { name: 'All', exact: true }).click();
  await eventually(async () => await page.locator('.log-card').count() === 3, 'Mobile all filter did not render');
  await page.screenshot({ path: 'output/mobile-journal-open.png' });
  await page.getByRole('button', { name: 'An edited memory', exact: false }).click();
  await eventually(async () => !await journal.evaluate(panel => panel.open) && await page.locator('.detail-panel h2').textContent() === 'An edited memory', 'Mobile memory selection did not open details');
  check(await page.locator('.detail-panel').isVisible(), 'Selecting a mobile journal entry collapses the journal and opens its details');
  await page.getByRole('button', { name: 'Close memory' }).click();
  await summary.click();await page.getByRole('button', { name: 'Wishlist', exact: true }).focus();await page.keyboard.press('Escape');
  check(!await journal.evaluate(panel => panel.open) && await summary.evaluate(element => element === document.activeElement), 'Escape collapses the journal and returns focus to its metrics');
  await summary.click();await summary.click();
  check(!await journal.evaluate(panel => panel.open), 'Tapping the metrics again collapses the full journal');
  await page.setViewportSize({ width: 390, height: 568 });await summary.click();
  check(await page.locator('.journal-content').evaluate(element => getComputedStyle(element).overflowY === 'auto' && element.scrollHeight > element.clientHeight), 'Full journal scrolls within a short mobile viewport');
  await page.setViewportSize({ width: 1440, height: 960 });
  await eventually(async () => await journal.evaluate(panel => panel.open) && !await summary.isVisible(), 'Returning to desktop did not restore the sidebar');
  check(await page.locator('.journal-panel .stats').isVisible() && await page.locator('.log-list .log-card').first().isVisible(), 'Resizing to desktop restores the existing full journal layout');
  await page.setViewportSize({ width: 390, height: 844 });
  await eventually(async () => !await journal.evaluate(panel => panel.open), 'Returning to mobile did not restore compact mode');
  await theme('dark'); await page.screenshot({ path: 'output/mobile-dark-world.png' }); check(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'Dark mobile layout fits viewport');
  await page.getByRole('button', { name: 'Add a wish', exact: false }).click();
  await page.getByLabel('Title', { exact: true }).fill('Lisbon someday');await page.getByLabel('City', { exact: true }).fill('Lisbon');await page.getByLabel('Country', { exact: true }).fill('Portugal');
  await page.getByRole('button', { name: 'Save wish' }).click();
  await eventually(async () => !await page.locator('.modal').count() && (await page.locator('.journal-metrics strong').allTextContents()).join(',') === '2,2,2', 'Compact metrics did not update after saving a wish');
  check(!await journal.evaluate(panel => panel.open), 'Saving a new mobile wish updates compact metrics without expanding the journal');
  await page.getByRole('button', { name: 'Close memory' }).click();
  await summary.click();await page.screenshot({ path: 'output/mobile-dark-journal-open.png' });await summary.click();
  await page.getByRole('button', { name: 'Sign out', exact: true }).click(); await page.waitForURL(base + '/login'); checks++;
  check(errors.length === 0, 'No browser script errors: ' + errors.join('; '));
  check(cssFailures.length === 0, 'All requested companion stylesheets were served successfully');
  console.log(`Passed ${checks} browser checks; screenshots saved under output/.`);
} catch (error) { await mkdir('output', { recursive: true }); await page.screenshot({ path: 'output/browser-failure.png', fullPage: true }).catch(() => { }); throw error; } finally { await browser.close(); }
